places = ['London', 'Paris', 'New York', 'Ottawa', 'Berlin']
print(f"Original list {places}")
print(f"Sorted list {sorted(places)}")
print(f"Original list {places}")
print(sorted(places, reverse=True))
print(f"Original list {places}")
places.reverse()
print(places)
places.reverse()
print(places)
places.sort()
print(f"Sort list {places}")
places.sort(reverse=True)
print(f"Reverse sort list {places}")